project:
  type: website
  output-dir: docs 
website:
  title: "Stephanie Farmer"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resources.qmd
      - projects.qmd
  page-footer:
    background: light 
    left: Copyright 2025, Stephanie Farmer
    right: This website is built with {{< fa brands github title="The GitHub octocat logo" >}}[{{< fa brands r-project title="R Project" >}}] and [Quarto](https://quarto.org/){target=_blank}
format:
  html:
    theme: styles.scss
    mainfont: Farsan
    css: styles.css
    toc: true
    page-layout: full
editor: visual

