project:
  type: website
output-dir: docs
website:
  title: "Stephanie Farmer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resources.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full
editor: visual

